### ISSUE TITLE
 2020 TN-SCUI dataset

### ISSUE THREAD

**Issue by baba1587** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#7]
where can i download this dataset ?
i need your help.

**Comment by baba1587** [comment]
thank you

**Comment by WAMAWAMA** [comment]
hi baba1587
info about the TN-SCUI dataset， please refer to this issue #1

**Comment by hlyf-xs** [comment]
Hello，I can't have the permission to download this dataset from the official website. So I really want to you can help me. Thank you!

**Comment by WAMAWAMA** [comment]
@hlyf-xs 
hi hlyf-xs
info about the TN-SCUI dataset， please refer to this issue #1 
**Since the sponsor of TNSCUI challenge does not allow the dissemination of the 2020 TN-SCUI dataset, we give another thyroid ultrasound dataset demo for your reference. The demo dataset was derived from the DDTI open-access dataset, and we have processed the dataset into the format of 2020 TN-SCUI dataset**

**Comment by hlyf-xs** [comment]
&nbsp; &nbsp; &nbsp; 您好！主要是想尝试用这个数据集做毕业论文，现在已经11月了，之前的一个方案没有走通。分类 + 分割只有这个数据集才正好合适，真的很需要这个原始数据集。您能不能分享一下？也可以买这个数据集，有什么条件，只要我们能够接受都是可以谈的！谢谢，打扰您了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WAMAWAMA/TNSCUI2020-Seg-Rank1st"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月18日(星期三) 上午10:57
收件人:&nbsp;"WAMAWAMA/TNSCUI2020-Seg-Rank1st"<TNSCUI2020-Seg-Rank1st@noreply.github.com&gt;;
抄送:&nbsp;"海浪一方"<2397585063@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [WAMAWAMA/TNSCUI2020-Seg-Rank1st]  2020 TN-SCUI dataset (#7)





 
@hlyf-xs
 hi hlyf-xs
 info about the TN-SCUI dataset， please refer to this issue #1
 Since the sponsor of TNSCUI challenge does not allow the dissemination of the 2020 TN-SCUI dataset, we give another thyroid ultrasound dataset demo for your reference. The demo dataset was derived from the DDTI open-access dataset, and we have processed the dataset into the format of 2020 TN-SCUI dataset

**Comment by WAMAWAMA** [comment]
> &nbsp; &nbsp; &nbsp; 您好！主要是想尝试用这个数据集做毕业论文，现在已经11月了，之前的一个方案没有走通。分类 + 分割只有这个数据集才正好合适，真的很需要这个原始数据集。您能不能分享一下？也可以买这个数据集，有什么条件，只要我们能够接受都是可以谈的！谢谢，打扰您了！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "WAMAWAMA/TNSCUI2020-Seg-Rank1st" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月18日(星期三) 上午10:57 收件人:&nbsp;"WAMAWAMA/TNSCUI2020-Seg-Rank1st"<TNSCUI2020-Seg-Rank1st@noreply.github.com&gt;; 抄送:&nbsp;"海浪一方"<2397585063@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [WAMAWAMA/TNSCUI2020-Seg-Rank1st] 2020 TN-SCUI dataset (#7) @hlyf-xs hi hlyf-xs info about the TN-SCUI dataset， please refer to this issue #1 Since the sponsor of TNSCUI challenge does not allow the dissemination of the 2020 TN-SCUI dataset, we give another thyroid ultrasound dataset demo for your reference. The demo dataset was derived from the DDTI open-access dataset, and we have processed the dataset into the format of 2020 TN-SCUI dataset — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

甲状腺数据确实很少，建议尝试乳腺超声结节数据，一样有分割和分类，公共数据集有很多👍
